name: Reusable Slack message
description: "Sends a message to a Slack channel using a webhook"
inputs:
  slack-webhook-url:
    description: "Slack Webhook URL"
    required: true
  message:
    description: "Message to send to Slack"
    required: true
  channel:
    description: "Slack channel to send the message to"
    required: true
  username:
    description: "Username to display in Slack"
    required: false

runs:
  using: "composite"
  steps:
    - run: |
        if [ -z "${{ inputs.slack-webhook-url }}" ]; then
          echo "Error: slack-webhook-url is required"
          exit 1
        fi
        if [ -z "${{ inputs.message }}" ]; then
          echo "Error: message is required"
          exit 1
        fi
        if [ -z "${{ inputs.channel }}" ]; then
          echo "Error: channel is required"
          exit 1
        fi
      shell: bash

    - name: Notify Slack
      shell: bash
      run: |
        result=$(curl --silent -d '{"channel": "${{ inputs.slack-channel }}", "text": "${{ inputs.message }}"}' -H "Content-type: application/json; charset=utf-8" -H "Authorization: Bearer $SLACK_API_TOKEN" "https://slack.com/api/chat.postMessage")
        ok=$(echo "$result" | jq -r '.ok')

        if [[ "$ok" == 'true' ]]; then
          echo "Sent message to slack channel ${{ inputs.slack-channel }}."
        else
          error=$(echo "$result" | jq -r '.error')

          if [[ $"error" == 'not_in_channel' ]]; then
            echo $'::error::\x40Github Workflow Notifications does not have access to the channel ${{ inputs.slack-channel }}, please add it to the channel.'
          else
            echo "$result" | jq '.'
          fi
        fi
      env:
        SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
